on:
  workflow_dispatch:
  schedule:
    # Run at 12:05 Monday - Fridays
    - cron:  '05 12 * * 1-5'

name: Version Checker

jobs:
  simple-check-playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Simplify Fetch Data
        run: curl -s GET https://api.github.com/repos/microsoft/playwright/tags\?per_page\=1 | jq -r '.[].name' > version.txt
    
      - name: Save Version as Variable
        id: version_variable
        run: echo "version=$(cat version.txt)" >> $GITHUB_ENV
     
      - name: Cache playwright version number
        uses: actions/cache@v3
        id: playwright-version
        with:
          path: |
            ./version.txt
          key: playwright-${{ env.version }}

      - name: Notify if version.txt has changed
        if: steps.playwright-version.outputs.cache-hit != 'true'
        uses: 8398a7/action-slack@v3
        with:
          text: 'A new version of Playwright has been released! https://github.com/microsoft/playwright/releases/tag/${{ steps.playwright-version.outputs.version }}'
          status: ${{ job.status }}
          fields: workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
